commit mysql data
xuguanhua/xmtgzs pull request #10
Opened 2018-03-25 14:17 UTC by xuguanhua

2018-03-25 14:33 UTC, XCapsule commented on community_recruit.sql
> +  `state` varchar(1) NOT NULL DEFAULT '0' COMMENT '表示社团的审核状态；0表示未审核，1表示审核中，2表示审核通过，3表示审核未通过',
用int字段表示state

2018-03-25 14:42 UTC, XCapsule requested changes

2018-03-25 14:42 UTC, XCapsule commented on community_recruit.sql
> +  `readed` varchar(255) NOT NULL DEFAULT '0' COMMENT '是否已经查看；0表示没有查看，1表示已经查看',
用tinyint字段表示readed

2018-03-25 14:42 UTC, XCapsule commented on community_recruit.sql
> +  `message_state` varchar(1) NOT NULL DEFAULT '0' COMMENT '是否需要发送message;0不需要，1待发送，2发送成功，3发送失败',
用tinyint类型

2018-03-25 14:42 UTC, XCapsule commented on community_recruit.sql
> +  `state` int(1) unsigned NOT NULL COMMENT '招新状态，1表示招新仍在继续，0表示招新结束',
用tinyint

2018-03-25 14:42 UTC, XCapsule commented on community_recruit.sql
> +  `message` varchar(255) NOT NULL COMMENT '短信信息',
comment `消息内容`

2018-03-25 14:42 UTC, XCapsule commented on community_recruit.sql
> +  `interview_time` datetime NOT NULL COMMENT '表示面试时间',
改名为interview_date

2018-03-25 16:36 UTC, XCapsule requested changes

2018-03-25 16:36 UTC, XCapsule commented on community_recruit.sql
> +CREATE TABLE `community_messages` (
缺一个created_at字段，记录创建时间

2018-03-25 16:36 UTC, XCapsule commented on community_recruit.sql
> +CREATE TABLE `recruit` (
缺一个created_at字段，记录申请创建时间

2018-03-25 16:36 UTC, XCapsule commented on community_recruit.sql
> +CREATE TABLE `recruit_times` (
缺一个created_at字段，记录招新时间，TIMESTAMP，default CURRENT_TIMESTAMP

2018-03-26 01:00 UTC, xuguanhua commented on community_recruit.sql
> +  `state` varchar(1) NOT NULL DEFAULT '0' COMMENT '表示社团的审核状态；0表示未审核，1表示审核中，2表示审核通过，3表示审核未通过',
好的

2018-03-26 05:11 UTC, XCapsule approved these changes

2018-03-26 05:11 UTC, merged