add a jdbcUtil file and a properties file
xuguanhua/xmtgzs pull request #11
Opened 2018-03-26 08:58 UTC by xuguanhua

jdbcUtil工具类

2018-03-26 15:04 UTC, XCapsule requested changes

2018-03-26 15:04 UTC, XCapsule commented on src/cn/edu/ncu/newmedia/dao/DBServlet.java
>  public class DBServlet {
这个类不该叫dbservlet，要和数据库表名保持一致，叫做CommunityAccountDao

2018-03-26 15:04 UTC, XCapsule commented on src/cn/edu/ncu/newmedia/dao/DBServlet.java
> +			//JdbcUtil.closeResource(conn, rs, stmt);
删掉这个注释

2018-03-27 05:32 UTC, xuguanhua commented on src/cn/edu/ncu/newmedia/dao/DBServlet.java
>  public class DBServlet {
哦，我改一下

2018-03-28 14:25 UTC, XCapsule approved these changes

2018-03-28 14:33 UTC, merged